application: commanigy-diary
version: 1
runtime: go
api_version: go1

inbound_services:
- mail

builtins:
- remote_api: on

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /mails/daily
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
